### ISSUE TITLE
New map says I've already mapped a structure.

### ISSUE THREAD

**Issue by dragon3025** [Shadows-of-Fire/Magical-Map#2]
While using creative, and discarded a map mapped to the ocean monument. When I went to make another it said I've already mapped it. I tried mapping the new map to the woodland mansion, and then back to the ocean monument, but it didn't work.

**Comment by Shadows-of-Fire** [comment]
I meant to respond to this earlier but apparently I didn't hit the send button.

Anyhow, that's working as intended.
